SELECT 
	tipo_notificacao
,	id_agravo
,	data_notificacao
--,	semana_notificacao
--,	sigla_uf_notificacao
--,	sigla_uf_notificacao_nome
,	id_regional_saude_notificacao
,	id_municipio_notificacao
--,	id_municipio_notificacao_nome
,	id_estabelecimento as id_cnes
,	data_primeiros_sintomas
,	semana_sintomas
,	pais_residencia
--,	sigla_uf_residencia
--,	sigla_uf_residencia_nome
--,	id_regional_saude_residencia
-,	id_municipio_residencia
--,	id_municipio_residencia_nome
,	ano_nascimento_paciente
,	data_nascimento_paciente
,	idade_paciente
,	sexo_paciente
,	raca_cor_paciente
,	escolaridade_paciente
,	ocupacao_paciente
,	ocupacao_paciente_descricao
,	ocupacao_paciente_descricao_familia
,	ocupacao_paciente_descricao_subgrupo
,	ocupacao_paciente_descricao_subgrupo_principal
,	ocupacao_paciente_descricao_grande_grupo
,	gestante_paciente
,	possui_doenca_autoimune
,	possui_diabetes
,	possui_doencas_hematologicas
,	possui_hepatopatias
,	possui_doenca_renal
,	possui_hipertensao
,	possui_doenca_acido_peptica
,	paciente_vacinado
--,	data_vacina
,	data_investigacao
,	apresenta_febre
,	data_febre
,	duracao_febre
,	apresenta_cefaleia
,	apresenta_exantema
,	apresenta_dor_costas
,	apresenta_prostacao
,	apresenta_mialgia
,	apresenta_vomito
,	apresenta_nausea
,	apresenta_diarreia
,	apresenta_conjutivite
,	apresenta_dor_retroorbital
,	apresenta_artralgia
,	apresenta_artrite
,	apresenta_leucopenia
,	apresenta_epistaxe
,	apresenta_petequias
,	apresenta_gengivorragia
,	apresenta_metrorragia
,	apresenta_hematuria
,	apresenta_sangramento
,	apresenta_complicacao
,	apresenta_ascite
,	apresenta_pleurite
,	apresenta_pericardite
,	apresenta_dor_abdominal
,	apresenta_hepatomegalia
,	apresenta_miocardite
,	apresenta_hipotensao
,	apresenta_choque
,	apresenta_insuficiencia_orgao
,	apresenta_sintoma_outro
,	apresenta_qual_sintoma
,	prova_laco
,	internacao
,	data_internacao
--,	sigla_uf_internacao
--,	sigla_uf_internacao_nome
,	id_municipio_internacao
--,	id_municipio_internacao_nome
,	alarme_hipotensao
,	alarme_plaqueta
,	alarme_vomito
,	alarme_sangramento
,	alarme_hematocrito
,	alarme_dor_abdominal
,	alarme_letargia
,	alarme_hepatomegalia
,	alarme_liquidos
,	data_alarme
,	grave_pulso
,	grave_convulsao
,	grave_enchimento_capilar
,	grave_insuficiencia_respiratoria
,	grave_taquicardia
,	grave_extremidade_fria
,	grave_hipotensao
,	grave_hematemese
,	grave_melena
,	grave_metrorragia
,	grave_sangramento
,	grave_ast_alt
,	grave_miocardite
,	grave_consciencia
,	grave_orgaos
,	data_hematocrito
,	hematocrito_maior
,	data_plaquetas
,	plaqueta_maior
,	data_hematocrito_2
,	hematocrito_menor
,	data_plaquetas_2
,	plaqueta_menor
,	data_sorologia1_chikungunya
,	data_resultado_sorologia1_chikungunya
,	resultado_sorologia1_chikungunya
,	sorologia1_igm
,	sorologia1_igg
,	sorologia1_tit1
,	resultado_sorologia2_chikungunya
,	sorologia2_igm
,	sorologia2_igg
,	sorologia2_tit1
,	resultado_prnt
,	data_ns1
,	resultado_ns1
,	data_viral
,	resultado_viral
,	data_pcr
,	resultado_pcr
,	amostra_pcr
,	amostra_outra
,	tecnica
,	resultado_amostra_outra
,	data_sorologia_dengue
,	resultado_sorologia_dengue
,	sorotipo
,	histopatologia
,	imunohistoquimica
,	manifestacao_hemorragica
,	classificacao_final
,	criterio_confirmacao
,	caso_fhd
,	caso_autoctone
,	pais_infeccao
--,	sigla_uf_infeccao
--,	sigla_uf_infeccao_nome
,	id_municipio_infeccao
--,	id_municipio_infeccao_nome
,	doenca_trabalho
,	apresentacao_clinica
,	evolucao_caso
--,	data_obito
--,	data_encerramento
,	tipo_sistema
--,	data_digitacao
,  (CASE WHEN LOWER(classificacao_final) LIKE '%dengue%' THEN 1 ELSE 0 END) AS target
,  (CASE WHEN LOWER(evolucao_caso) LIKE '%óbito%' THEN 1 ELSE 0 END) AS obito
,  (CASE WHEN data_encerramento is not null THEN 1  ELSE 0  END) AS flag_caso_encerrado

---Dias
, (CASE 
        WHEN data_encerramento is not null and data_encerramento>=data_notificacao
        THEN  datediff(day,data_notificacao,data_encerramento)  
        ELSE null  END) as qt_dias_encerramento
,count(*) as qt

from `basedosdados.br_ms_sinan.microdados_dengue`
where 1=1
and ano>=2021
group by 
tipo_notificacao
,	id_agravo
,	data_notificacao
--,	semana_notificacao
--,	sigla_uf_notificacao
--,	sigla_uf_notificacao_nome
,	id_regional_saude_notificacao
,	id_municipio_notificacao
--,	id_municipio_notificacao_nome
,	id_estabelecimento as id_cnes
,	data_primeiros_sintomas
,	semana_sintomas
,	pais_residencia
--,	sigla_uf_residencia
--,	sigla_uf_residencia_nome
--,	id_regional_saude_residencia
-,	id_municipio_residencia
--,	id_municipio_residencia_nome
,	ano_nascimento_paciente
,	data_nascimento_paciente
,	idade_paciente
,	sexo_paciente
,	raca_cor_paciente
,	escolaridade_paciente
,	ocupacao_paciente
,	ocupacao_paciente_descricao
,	ocupacao_paciente_descricao_familia
,	ocupacao_paciente_descricao_subgrupo
,	ocupacao_paciente_descricao_subgrupo_principal
,	ocupacao_paciente_descricao_grande_grupo
,	gestante_paciente
,	possui_doenca_autoimune
,	possui_diabetes
,	possui_doencas_hematologicas
,	possui_hepatopatias
,	possui_doenca_renal
,	possui_hipertensao
,	possui_doenca_acido_peptica
,	paciente_vacinado
--,	data_vacina
,	data_investigacao
,	apresenta_febre
,	data_febre
,	duracao_febre
,	apresenta_cefaleia
,	apresenta_exantema
,	apresenta_dor_costas
,	apresenta_prostacao
,	apresenta_mialgia
,	apresenta_vomito
,	apresenta_nausea
,	apresenta_diarreia
,	apresenta_conjutivite
,	apresenta_dor_retroorbital
,	apresenta_artralgia
,	apresenta_artrite
,	apresenta_leucopenia
,	apresenta_epistaxe
,	apresenta_petequias
,	apresenta_gengivorragia
,	apresenta_metrorragia
,	apresenta_hematuria
,	apresenta_sangramento
,	apresenta_complicacao
,	apresenta_ascite
,	apresenta_pleurite
,	apresenta_pericardite
,	apresenta_dor_abdominal
,	apresenta_hepatomegalia
,	apresenta_miocardite
,	apresenta_hipotensao
,	apresenta_choque
,	apresenta_insuficiencia_orgao
,	apresenta_sintoma_outro
,	apresenta_qual_sintoma
,	prova_laco
,	internacao
,	data_internacao
--,	sigla_uf_internacao
--,	sigla_uf_internacao_nome
,	id_municipio_internacao
--,	id_municipio_internacao_nome
,	alarme_hipotensao
,	alarme_plaqueta
,	alarme_vomito
,	alarme_sangramento
,	alarme_hematocrito
,	alarme_dor_abdominal
,	alarme_letargia
,	alarme_hepatomegalia
,	alarme_liquidos
,	data_alarme
,	grave_pulso
,	grave_convulsao
,	grave_enchimento_capilar
,	grave_insuficiencia_respiratoria
,	grave_taquicardia
,	grave_extremidade_fria
,	grave_hipotensao
,	grave_hematemese
,	grave_melena
,	grave_metrorragia
,	grave_sangramento
,	grave_ast_alt
,	grave_miocardite
,	grave_consciencia
,	grave_orgaos
,	data_hematocrito
,	hematocrito_maior
,	data_plaquetas
,	plaqueta_maior
,	data_hematocrito_2
,	hematocrito_menor
,	data_plaquetas_2
,	plaqueta_menor
,	data_sorologia1_chikungunya
,	data_resultado_sorologia1_chikungunya
,	resultado_sorologia1_chikungunya
,	sorologia1_igm
,	sorologia1_igg
,	sorologia1_tit1
,	resultado_sorologia2_chikungunya
,	sorologia2_igm
,	sorologia2_igg
,	sorologia2_tit1
,	resultado_prnt
,	data_ns1
,	resultado_ns1
,	data_viral
,	resultado_viral
,	data_pcr
,	resultado_pcr
,	amostra_pcr
,	amostra_outra
,	tecnica
,	resultado_amostra_outra
,	data_sorologia_dengue
,	resultado_sorologia_dengue
,	sorotipo
,	histopatologia
,	imunohistoquimica
,	manifestacao_hemorragica
,	classificacao_final
,	criterio_confirmacao
,	caso_fhd
,	caso_autoctone
,	pais_infeccao
--,	sigla_uf_infeccao
--,	sigla_uf_infeccao_nome
,	id_municipio_infeccao
--,	id_municipio_infeccao_nome
,	doenca_trabalho
,	apresentacao_clinica
,	evolucao_caso
--,	data_obito
--,	data_encerramento
,	tipo_sistema
--,	data_digitacao
,qt_dias_encerramento